using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Global.Models
{
    public class RoleToMenuViewModel
    {
        [Display(Name = "RoleName")]
        public String? RoleName { get; set; }

        [Display(Name = "MenuItems")]
        public List<SelectListItem>? MenuItems { get; set; }
    }

    public class RoleToReportViewModel
    {
        [Display(Name = "RoleName")]
        public String? RoleName { get; set; }

        [Display(Name = "MenuItems")]
        public List<SelectListItem>? ReportsList { get; set; }
    }

    public class ReportsViewModel
    {
        [Display(Name = "syReports-ID", Description = "syReports-ID.")]
        [Key]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public Int32 ID { get; set; }

        [Display(Name = "syReports-Subsystem", Description = "syReports-Subsystem.")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public Int32 Subsystem { get; set; }

        [Display(Name = "ReportName")]
        public String? Name { get; set; }
    }

    /// <summary>
    /// take same model as the jstree record needs
    /// // Expected format of the node (there are no required fields)
    ////{
    ////  id          : "string" // will be autogenerated if omitted
    ////  text        : "string" // node text
    ////  icon        : "string" // string for custom
    ////  state       : {
    ////    opened    : boolean  // is the node open
    ////    disabled  : boolean  // is the node disabled
    ////    selected  : boolean  // is the node selected
    ////},
    ////  children    : []  // array of strings or objects
    ////li_attr     : {}  // attributes for the generated LI node
    ////  a_attr      : {}  // attributes for the generated A node
    ////}
    /// </summary>

    public class JsTreeModel
    {
        public String? id { get; set; }
        public String? parent { get; set; }
        public String? text { get; set; }
        public String? icon { get; set; }
        public String? state { get; set; }
        public bool opened { get; set; }
        public bool disabled { get; set; }
        public bool selected { get; set; }
        public String? li_attr { get; set; }
        public String? a_attr { get; set; }
    }
}